name: Publish Docker Container as GitHub Package

on:
  push:
    branches:
      - main
  workflow_dispatch: # Added manual trigger
  release: # Triggered when a new release is created
    types: [created]

jobs:
  build-and-publish:
    name: Build and Publish Docker Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          DOCKER_TAG=${GITHUB_REF/refs\/tags\//}
          docker build . -t ghcr.io/${{ github.repository }}:$DOCKER_TAG

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image to GitHub Package
        run: |
          DOCKER_TAG=${GITHUB_REF/refs\/tags\//}
          docker push ghcr.io/${{ github.repository }}:$DOCKER_TAG
