name: Publish Docker Container as GitHub Package

on:
  push:
    branches:
      - main
  workflow_dispatch: # Added manual trigger

jobs:
  build-and-publish:
    name: Build and Publish Docker Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build . -t ${{ github.repository }}:${{ github.sha }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image to GitHub Package
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository }}:${{ github.sha }}"
          docker tag $IMAGE_ID $IMAGE_ID
          docker push $IMAGE_ID
